"""Removed is_star_meal column to meals

Revision ID: 59ecc85c332d
Revises: bab47ab42faa
Create Date: 2023-11-09 04:07:59.776898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ecc85c332d'
down_revision = 'bab47ab42faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('is_star_meal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_star_meal', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
