"""Added is_star_meal column to meals

Revision ID: bab47ab42faa
Revises: c40901840818
Create Date: 2023-11-09 00:00:40.951881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab47ab42faa'
down_revision = 'c40901840818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_star_meal', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('is_star_meal')

    # ### end Alembic commands ###
